In [4]:
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.preprocessing import MultiLabelBinarizer

# Contoh DataFrame
data = {
    'title': ['Film A', 'Film B', 'Film C'],
    'genres': [[0, 1, 2], [1, 2], [0, 2]]
}

df = pd.DataFrame(data)

# Menggunakan MultiLabelBinarizer untuk mengubah list menjadi format numerik
mlb = MultiLabelBinarizer()
genres_encoded = mlb.fit_transform(df['genres'])

# Menghitung cosine similarity
similarity_matrix = cosine_similarity(genres_encoded)

print(genres_encoded)

[[1 1 1]
 [0 1 1]
 [1 0 1]]


In [4]:
import pandas as pd
import numpy as np

# Contoh DataFrame
data = {
    'film': ['Film A', 'Film B', 'Film C'],
    'fitur_1': [1, 2, 0],
    'fitur_2': [0., 1, 1],
    'fitur_3': [1., 1., 1.]
}

df = pd.DataFrame(data)

def cosine_similarity(df):
    # Ambil nilai fitur tanpa kolom 'film'
    feature_matrix = df.iloc[:, 1:].values
    
    # Hitung dot product antara vektor
    dot_product = np.dot(feature_matrix, feature_matrix.T)
    
    # Hitung norma (magnitudo) dari setiap vektor
    norms = np.linalg.norm(feature_matrix, axis=1)
    
    # Hitung cosine similarity
    cosine_sim = dot_product / np.outer(norms, norms)
    
    return cosine_sim

# Menghitung cosine similarity
similarity_matrix = cosine_similarity(df)
similarity_df = pd.DataFrame(similarity_matrix, index=df['film'], columns=df['film'])

print("Cosine Similarity Matrix:")
print(similarity_df)


Cosine Similarity Matrix:
film      Film A    Film B   Film C
film                               
Film A  1.000000  0.866025  0.50000
Film B  0.866025  1.000000  0.57735
Film C  0.500000  0.577350  1.00000
